<a href="https://colab.research.google.com/github/lafontes/Analise-dados-vendas-Python/blob/main/Vendas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [130]:
# Usar Python para percorrer os arquivos de dados nas pastas.

import os
import pandas as pd


lista_arquivos = os.listdir(f"/content/drive/MyDrive/Relatório de vendas/Vendas")
display(lista_arquivos)

['Vendas - Goiás.csv',
 'Vendas - Porto Alegre.csv',
 'Vendas - Belo Horizonte.csv',
 'Vendas - Recife.csv',
 'Devolucoes - Goiás.csv',
 'Devolucoes - Belo Horizonte.csv',
 'Devolucoes - Rio de Janeiro.csv',
 'Devolucoes - Curitiba.csv',
 'Vendas - Rio de Janeiro.csv',
 'Devolucoes - Porto Alegre.csv',
 'Vendas - Fortaleza.csv',
 'Devolucoes - São Paulo.csv',
 'Devolucoes - Fortaleza.csv',
 'Vendas - Salvador.csv',
 'Devolucoes - Salvador.csv',
 'Vendas - São Paulo.csv',
 'Devolucoes - Recife.csv',
 'Vendas - Curitiba.csv']

In [131]:
tabela_total = pd.DataFrame()

#Importar a base de dados de vendas.

# Criar uma lista para armazenar os DataFrames de vendas
listas_tabelas = []

for arquivo in lista_arquivos:
  if "Vendas" in arquivo:
    #Importar arquivos.
    tabela = pd.read_csv(f"/content/drive/MyDrive/Relatório de vendas/Vendas/{arquivo}")
    listas_tabelas.append(tabela)

# Concatenar todos os DataFrames de uma vez
tabela_total = pd.concat(listas_tabelas)

display(tabela_total)

,Unnamed: 0,SKU,Produto,Quantidade Vendida,Primeiro Nome,Sobrenome,Data,Loja,Preco Unitario,Unnamed: 8
0,13,HL4379,Televisão,1,Daniel,Monteiro,5/23/2018,Goiás,2500,NaN
1,19,HL9962,Android,4,Elaine,Santos,7/5/2018,Goiás,3400,NaN
2,45,HL1918,iPhone,5,Lenon,Fernandes,3/31/2018,Goiás,5300,NaN
3,50,HL7348,SmartWatch,1,Vivianne,Rodrigues,8/11/2018,Goiás,1400,NaN
4,97,HL7348,SmartWatch,2,Pedro,Rodrigues,7/26/2018,Goiás,1400,NaN
...,...,...,...,...,...,...,...,...,...,...
714,9859,HL2714,Tablet,1,Júlio,Fraga,12/25/2018,Curitiba,1600,NaN
715,9876,HL4379,Televisão,5,Bruno,Mota,4/30/2018,Curitiba,2500,NaN
716,9918,HL1148,Câmera,2,Lucas,Reis,12/27/2018,Curitiba,2100,NaN
717,9944,HL1918,iPhone,5,Raphael,Kurtz,7/16/2018,Curitiba,5300,NaN
718,9998,HL7348,SmartWatch,1,Vinícius,Antunes,12/10/2018,Curitiba,1400,NaN

In [132]:
#Calcular produtos mais vendidos em ordem crescente.
tabela_produtos = tabela_total.groupby('Produto').sum()
tabela_produtos = tabela_produtos[['Quantidade Vendida','Preco Unitario']].sort_values(by="Quantidade Vendida", ascending=False)
display(tabela_produtos)

            Quantidade Vendida  Preco Unitario
Produto
iPhone                    8974        15778100
Televisão                 5931         4905000
Notebook                  3249         3717000
Android                   3183         3631200
SmartWatch                2980         1393000
Tablet                    2921         1556800
Câmera                    2805         2020200

In [133]:
#Calcular o produto que mais faturou
tabela_total['Faturamento'] = tabela_total['Quantidade Vendida'] * tabela_total['Preco Unitario']

tabela_faturamento = tabela_total.groupby('Produto').sum()
tabela_faturamento = tabela_faturamento[['Faturamento']].sort_values(by="Faturamento", ascending=False)

display(tabela_faturamento)

            Faturamento
Produto
iPhone         47562200
Televisão      14827500
Notebook       11371500
Android        10822200
Câmera          5890500
Tablet          4673600
SmartWatch      4172000

In [134]:
# Calcular a loja que mais vendeu em faturamento
tabela_lojas = tabela_total.groupby('Loja').sum()
tabela_lojas = tabela_lojas [['Faturamento']].sort_values(by="Faturamento", ascending=False)
display(tabela_lojas)

                Faturamento
Loja
São Paulo          22098300
Rio de Janeiro     14867800
Fortaleza          14087900
Salvador           13111300
Goiás               7441800
Recife              7303000
Curitiba            7060500
Porto Alegre        6868600
Belo Horizonte      6480300

In [137]:
import plotly.express as px

df = px.data.tips()
grafico = px.bar(tabela_lojas, x=tabela_lojas.index, y='Faturamento')
grafico.show()

Passo a passo solucionando desafio.